import next from "next";
import globalstyle from '../../styles/Items.module.css';
import Head from "next/head";
import styles  from './style.module.css';
import { Menu } from "../compenents/Menu/Menu";
import { Navbar } from "../compenents/Menu/Menu";
import Footer from "../compenents/Footer/footer";
import { Session } from "inspector";

export default function Channel () {  
    return(
        <div className={globalstyle.container}>
             <Head>
            <title> Portifólio - Tv</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Menu/>
          <main className={globalstyle.main}>
           <section className={styles.container}>
             <div className={styles.conttopmedia}>
                
                <div className={styles.containerseach}>
                <input className={styles.contsearch}/>
                <div className={styles.btnseach}> Buscar </div>
                </div>
             </div>
              
               
  
           </section>
          </main>
          <Footer/>
          <Navbar/>
        </div>
      );
  }