import next from "next";
import Link from "next/link";
import Head from "next/head";
import styles from './style.module.css';
import globalstyle from '../../styles/global.module.css';
import Uis from "../Data/dataui/arraydatalist";
import Menu from "../compenents/Menu/Menu";
import Footer from "../compenents/Footer/footer";


export default function Uipage(){
 
    return (
    <div className={globalstyle.container}>
        <Head>
          <title>Portfolio Ui Design</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
     <Menu/>
    <div className={globalstyle.main}>
    <div className={styles.firstsection}>
          <div className={styles.title}><a> Ui Design </a></div>
          <div className={styles.description}>Interface prototyping is very exciting, here we have some projects that I have been updating, all created with Figma.</div>
    </div>
     <Uis/>
    </div>
    <Footer/>
  </div>
    )
 
}