import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



export default function Home() {

  const testebtn= () => {
    alert('ALERTA');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div className={styles.menutop}>Menu</div>
      <main className={styles.main}>
       <div className={styles.banner}>
       <div className={styles.contbannerinto} style={{width:'auto', paddingRight:'30px', paddingLeft:'30px', maxWidth:'512px'}} >
        <div className={styles.profilecard}>
         <Image
          src="/images/pjperson.png"
          alt="Descrição da imagem"
          width={140} 
          height={140} 
         />
         <line style={{fontSize:'18px', margin:'20px'}}>Paulo Vieira</line>

          <button className={styles.contbutton} onClick={testebtn} >
               <Image
                alt="Descrição da imagem"
               src="/whats.png"
               width={32}
               height={32}
               />
               <line style={{marginLeft:'10px'}}>
                 Fala comigo!
               </line>
          </button>
        </div>
        
           </div>
           <div className={styles.contbannerinto} style={{ maxWidth:'900px'}}>
           <div className={styles.line}>
           <div  className={styles.hi}><a> Hi, I’m UI Design and Front-end Developer.</a></div>
            </div>
            <div className={styles.line}>
              
            </div>
            <div className={styles.line}>
             
            </div>
           </div>
       </div>
       <div className={styles.contant}>
       <div className={styles.firstsection}>
            <div className={styles.title}><a> Hi, I’m UI Design and Front-end Developer.</a></div>
            <text className={styles.text}>Atualmente 40% dos nossos projetos são construídos a partir de material reciclado.  Atualmente 40% dos nossos projetos são construídos a partir de material reciclado. </text>
       </div>
       <div className={styles.secondsection}>
           <div className={styles.card}>
           <Image
              src="/ux.png" 
              alt="Descrição da imagem"
              width={48} 
              height={48} 
            />
            <div>UX Design </div>
             </div>
           <div className={styles.card}>
           <Image
              src="/pencil.png" 
              alt="Descrição da imagem"
              width={48} 
              height={48} 
            />
            <div>UI Design </div>
             </div>
           <div className={styles.card}> 
           <Image
              src="/code.png" 
              alt="Descrição da imagem"
              width={48} 
              height={48} 
            />
            <div>Front-End</div>
            </div>
           <div className={styles.card}> 
           <Image
              src="/server.png" 
              alt="Descrição da imagem"
              width={48} 
              height={48} 
            />
            <div>Back-End</div>
            </div>
       </div>
       </div>
       <div className={styles.firstsection} style={{paddingTop:'100px'}}>
            <div className={styles.title}><a>What I Am Great At </a></div>
            <text className={styles.text}>Atualmente 40% dos nossos projetos são construídos a partir de material reciclado.  Atualmente 40% dos nossos projetos são construídos a partir de material reciclado. </text>
       </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
