  import { useState, useEffect } from 'react';
  import Head from 'next/head'
  import Image from 'next/image'
  import styles from '../styles/Home.module.css'
  import Link from 'next/link';
  import Certification from './Data/certifications';
  import Menu from './compenents/Menu/Menu';
  import { Banner } from './compenents/Banner/banner';
  import { Footer } from './compenents/Footer/footer';

  export default function Home() {

    const [btnrotulo, setBetnRotulo] = useState ('');

  
    return (
      <div className={styles.container}>
        <Head>
          <title>Portifólio Paulo Vieira</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Menu/>
        <main className={styles.main}>

        <Banner/>

        <div className={styles.contant}>
          
          <section className={styles.contsesion}>
          <div className={styles.firstsection}>
          <div className={styles.title}><a> A little about myself </a></div>
          <div className={styles.text}>Owner of a very creative mind, quick to learn, analytical and hyperfocused on my goals, I love technology and its ability to promote change.</div>
          </div>
          <div className={styles.contmove}>
          <iframe
            width="640"
            height="360"
            src="https://www.youtube.com/embed/jX_CYgOKodg"
            title="YouTube Video Player"
            allowFullScreen/>
          </div>

        </section>
        
        <section className={styles.secondsection}>
        <div className={styles.firstsection}>
              <div className={styles.title}><a> how I can help your organization </a></div>
              <div className={styles.text}> Select how I can contribute to your project from the options below.</div>
        </div>
            <div className={styles.gridcontainer}>
          <Link href={"/pageux"} style={{width:'100%', height:'200px'}}>
            <div className={styles.card}>
            <Image
                src="/ux.png" 
                alt="Descrição da imagem"
                width={48} 
                height={48} 
              />
              <p>UX Design </p>
                </div>
            </Link>
            <Link href={"/pageui"} style={{width:'100%', height:'200px'}}>
            <div className={styles.card}>
            <Image
                src="/pencil.png" 
                alt="Descrição da imagem"
                width={48} 
                height={48} 
              />
              <p>UI Design </p>
              </div>
              </Link>
              <Link href={"/pagefrontend"} style={{width:'100%', height:'200px'}}> 
            <div className={styles.card}>
            <Image
                src="/code.png" 
                alt="Descrição da imagem"
                width={48} 
                height={48} 
              />
              <p>Front-End</p>
              </div>
              </Link>
              <Link href={"/pagebackend"}style={{width:'100%', height:'200px'}}> 
              <div className={styles.card}> 
              <Image
                src="/server.png" 
                alt="Descrição da imagem"
                width={48} 
                height={48} 
              />
              <p>Back-End</p>
            </div> </Link>
        </div>
        </section>
        </div>
        <section className={styles.secondsection}>
        <div className={styles.firstsection} style={{paddingTop:'20px'}}>
              <div className={styles.title}><a>Some courses and training</a></div>
              <div className={styles.text}>Check out some course and training certificates that help me develop an analytical and creative vision for projects.</div>
        </div>
        <div className={styles.certificationsGrid}>
            <Certification/>
        <div className={styles.linebass}>
        <div className={styles.btnseeall}> See all! </div> 
          </div> 
        </div>
        </section>
        </main>
       <Footer/>
        
      </div>
    )
  }
