import next from "next";
import Link from "next/link";
import Head from "next/head";
import styles from '../styles/Home.module.css';
import Uis from "./Data/dataui/arraydatalist";
import Menu from "./compenents/Menu/Menu";


export default function Uipage(){
 
    return (
    <div className={styles.container}>
        <Head>
          <title>Portifólio Ui Design</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
     <Menu/>
    <div className={styles.main}>
    <div className={styles.firstsection} style={{paddingTop:'30px'}}>
              <div className={styles.title}><a> Ui Design </a></div>
              <div className={styles.text}>Interface prototyping is very exciting, here we have some projects that I have been updating, all created with Figma.</div>
    </div>
     <Uis/>
    </div>
    <div className={styles.footer}></div>
  </div>
    )
 
}